#################################################################################
#                          *** datasetConfig.yaml ***                           #
#################################################################################
version : 1.05.200806

DIV2K_SR:
    origin: superResolution/SISR/DIV2K
    dataType: 
        LR: Image-Float #  dataName: dataType(InputType)-tensorType(OutputType)  (Text/Image/ImageSequence)-(Float/Int)    ->     Text->1D, Image->2D, ImageSequence->3D
    labelType:
        HR: Image-Float # (Text/Image/ImageSequence)-(Float/Int)
    availableMode: 
        - train
        - validation #train, validation, test
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - scaleMethod
        - scaleFactor
    preprocessings: # Must be list
        - Pass()

DIV2K_SR_V:
    origin: superResolution/SISR/DIV2K
    dataType: 
        LR: Image-Float #  dataName: dataType-tensorType  (Text/Image/ImageSequence)-(Float/Int)    ->     Text->1D, Image->2D, ImageSequence->3D
    labelType:
        HR: Image-Float # (Text/Image/ImageSequence)-(Float/Int)
    availableMode: 
        - train
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - class
    preprocessings: # Must be list
        - Pass()


291_SR:
    origin: superResolution/SISR/291
    dataType: 
        LR: Image-Float #  dataName: dataType-tensorType  (Text/Image/ImageSequence)-(Float/Int)    ->     Text->1D, Image->2D, ImageSequence->3D
    labelType:
        HR: Image-Float # (Text/Image/ImageSequence)-(Float/Int)
    availableMode: 
        - train
        - validation #train, validation, test
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - class
    preprocessings: # Must be list
        - Pass()


REDS_SR:
    origin: superResolution/MISR/REDS
    dataType: 
        LR: ImageSequence-Float #  dataName: dataType-tensorType  (Text/Image/ImageSequence)-(Float/Int)    ->     Text->1D, Image->2D, ImageSequence->3D
    labelType:
        HR: ImageSequence-Float # (Text/Image/ImageSequence)-(Float/Int)
    availableMode: 
        - train
        - validation #train, validation, test
        - test
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - degradationMethod
        - scaleFactor
    preprocessings: # Must be list
        - Pass()

VID4_SR:
    origin: superResolution/MISR/Vid4
    dataType: 
        LR: ImageSequence-Float #  dataName: dataType-tensorType  (Text/Image/ImageSequence)-(Float/Int)    ->     Text->1D, Image->2D, ImageSequence->3D
    labelType:
        HR: ImageSequence-Float # (Text/Image/ImageSequence)-(Float/Int)
    availableMode: 
        - test
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - degradationMethod
        - scaleFactor
    preprocessings: # Must be list
        - Pass()


FFHQ_FACE_SR_V:
    origin: domainDataset/face/FFHQ/Face
    dataType: 
        LR: Image-Float #  dataName: dataType-tensorType  (Text/Image/ImageSequence)-(Float/Int)    ->     Text->1D, Image->2D, ImageSequence->3D
    labelType:
        HR: Image-Float # (Text/Image/ImageSequence)-(Float/Int)
    availableMode:
        - train
        - test
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - class
    preprocessings: # Must be list
        - Pass()


Set5_SR:
    origin: superResolution/SISR/benchmark/Set5
    dataType: 
        LR: Image-Float #  dataName: dataType-tensorType  (Text/Image/ImageSequence)-(Float/Int)    ->     Text->1D, Image->2D, ImageSequence->3D
    labelType:
        HR: Image-Float # (Text/Image/ImageSequence)-(Float/Int)
    availableMode:
        - test
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - scaleMethod
        - scaleFactor
    preprocessings: # Must be list
        - Pass

Set5_SR_V:
    origin: superResolution/SISR/benchmark/Set5
    dataType: 
        LR: Image-Float #  dataName: dataType-tensorType  (Text/Image/ImageSequence)-(Float/Int)    ->     Text->1D, Image->2D, ImageSequence->3D
    labelType:
        HR: Image-Float # (Text/Image/ImageSequence)-(Float/Int)
    availableMode:
        - test
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - class
    preprocessings: # Must be list
        - Pass()

Set14_SR:
    origin: superResolution/SISR/benchmark/Set14
    dataType: 
        LR: Image-Float #  dataName: dataType-tensorType  (Text/Image/ImageSequence)-(Float/Int)    ->     Text->1D, Image->2D, ImageSequence->3D
    labelType:
        HR: Image-Float # (Text/Image/ImageSequence)-(Float/Int)
    availableMode:
        - test
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - scaleMethod
        - scaleFactor
    preprocessings: # Must be list
        - Pass()

Blending_SR:
    origin: superResolution/SISR/benchmark/Blending
    dataType: 
        LR: Image-Float #  dataName: dataType-tensorType  (Text/Image/ImageSequence)-(Float/Int)    ->     Text->1D, Image->2D, ImageSequence->3D
    labelType:
        HR: Image-Float # (Text/Image/ImageSequence)-(Float/Int)
    availableMode:
        - test
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - scaleMethod
        - scaleFactor
    preprocessings: # Must be list
        - Pass()

Satellite_DOTA_SR_V:
    origin: domainDataset/satellite/DOTA
    dataType: 
        LR: Image-Float #  dataName: dataType-tensorType  (Text/Image/ImageSequence)-(Float/Int)    ->     Text->1D, Image->2D, ImageSequence->3D
    labelType:
        HR: Image-Float # (Text/Image/ImageSequence)-(Float/Int)
    availableMode: 
        - train
        - validation
        - test
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - class
    preprocessings: # Must be list
        - Pass()

Satellite_xView_Building_SR_V:
    origin: domainDataset/satellite/xView_Building
    dataType: 
        LR: Image-Float #  dataName: dataType-tensorType  (Text/Image/ImageSequence)-(Float/Int)    ->     Text->1D, Image->2D, ImageSequence->3D
    labelType:
        HR: Image-Float # (Text/Image/ImageSequence)-(Float/Int)
    availableMode: 
        - train
        - validation
        - test
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - class
    preprocessings: # Must be list
        - Pass()

Medical_CXR8_V:
    origin: domainDataset/medical/CXR8
    dataType: 
        LR: Image-Float #  dataName: dataType-tensorType  (Text/Image/ImageSequence)-(Float/Int)    ->     Text->1D, Image->2D, ImageSequence->3D
    labelType:
        HR: Image-Float # (Text/Image/ImageSequence)-(Float/Int)
    availableMode: 
        - train
        - validation
        - test
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - class
    preprocessings: # Must be list
        - Pass()