#DEFINE "FIXED" Dataset Config
version : 1.03.200717

DIV2K_SR:
    origin: DIV2K
    dataType: 
        LR: 2D-Float # nD-(Float,Int)
    labelType:
        HR: 2D-Float # image, imagesequence, string
    availableMode: 
        - train
        - validation #train, validation, test
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - scaleMethod
        - scaleFactor
    preprocessings: 
        - RandomCrop
        - HFlip
        - VFlip
        - HueAdjust


DIV2K_AutoEncoder:
    origin: DIV2K
    dataType: 
        Image: 2D-Float
    labelType:  # image, imagesequence, string
    vailableMode: 
        - train
        - validation
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - sceneNumber
    preprocessings: 
        - RandomCrop
        - HFlip
        - VFlip
        - HueAdjust

        
