#DEFINE "FIXED" Dataset Config
version : 1.04.200729

DIV2K_SR:
    origin: DIV2K
    dataType: 
        LR: Image-Float #  dataName: dataType-tensorType  (Text/Image/ImageSequence)-(Float/Int)    ->     Text->1D, Image->2D, ImageSequence->3D
    labelType:
        HR: Image-Float # (Text/Image/ImageSequence)-(Float/Int)
    availableMode: 
        - train
        - validation #train, validation, test
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - scaleMethod
        - scaleFactor
    preprocessings: # Must be list


DIV2K_AutoEncoder:
    origin: DIV2K
    dataType: 
        Image: Image-Float
    labelType:  # (Text/Image/ImageSequence)-(Float/Int) 
    vailableMode: 
        - train
        - validation
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - sceneNumber
    preprocessings: 
        - RandomCrop()
        - HFlip()
        - VFlip()
        - HueAdjust()


