#################################################################################
#                          *** datasetConfig.yaml ***                           #
#################################################################################



#
# LPR
#

# LBLP
LBLP_SR :
    origin: domainDataset/LPR/LBLP
    dataType: Image
    classes: # Folder structure must be ... MAINPATH - Train/Valid/Test - Class[0](GT is Here) - ... - Class[N] - Scene
        - mode
        - scaleMethod
        - scaleFactor
    special:
        GT: '*/GT'
    preprocessings: # Must be list
        - Pass()



# AFA
LP_Unified_V:
    origin: NEW_LP_Other_datasets/Unified
    dataType: Image
    classes: 
        - mode
        - scaleMethod
    special:
        GT: '*/GT'
    preprocessings: # Must be list
        - Pass()

LP_China_V:
    origin: NEW_LP_Other_datasets/CCPD_OTHERS
    dataType: Image
    classes: 
        - mode
        - scaleMethod
    special:
        GT: '*/GT'
    preprocessings: # Must be list
        - Pass()

New_Lp_256_Blur_HR_V: ## GT는 HR Deblur, 학습 데이터는 x4Lr + blur
    origin: New_Lp_256_Blur_HR
    dataType: Image
    classes: 
        - mode
        - scaleMethod
    special:
        GT: '*/GT'
    preprocessings: # Must be list
        - Pass()

New_Lp_256_Blur_HR: ## GT는 HR Deblur, 학습 데이터는 x4Lr + blur
    origin: New_Lp_256_Blur_HR
    dataType: Image
    classes: 
        - mode
        - scaleMethod
        - scaleFactor
    special:
        GT: '*/GT'
    preprocessings: # Must be list
        - Pass()


