#################################################################################
#                               *** param.yaml ***                              #
#################################################################################
version : 2.02.200729
 




#################################################################################
#                                     GENERAL                                   #
#################################################################################
general:
    maxMemoryCachingSizeGB: 64
    maxVRAMCachingSizeGB: 8 # will be devide by # of GPU





#################################################################################
#                                       DATA                                    #
#################################################################################
data:
    path: 
        datasetPath: /home/projSR/dataset/
        pretrainedPath: /home/projSR/dataset/pretrained/
    
    datasetComponent:
        DIV2K_SR_train:
            dataConfig: DIV2K_SR
            mode: train # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                scaleMethod: 
                    - bicubic
                scaleFactor: 
                    - 4
            colorMode: color  # 'color' || 'grayscale'

        DIV2K_SR_train_virtual:
            dataConfig: DIV2K_SR_V
            mode: train # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                class: 
                    - GT
            colorMode: color  # 'color' || 'grayscale'

        291_SR_train:
            dataConfig: 291_SR
            mode: train
            classParameter:
                class: 
                    - GT
            colorMode: color
            #sequenceLength: 7 # Only for Image Sequence Dataset


    dataLoader:
        train_x:
            datasetComponent: # Must be list
                - DIV2K_SR_train
            batchSize: 32
            samplingCount: 1
            valueRangeType : -1~1
            shuffle: True
            makePreprocessedFile: True
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - centerCrop(96, 96)
                - sizeMatch()
                - toTensor()
        train:
            datasetComponent: # Must be list
                - 291_SR_train
                - DIV2K_SR_train_virtual
            batchSize: 30
            samplingCount: 1
            valueRangeType : -1~1
            shuffle: True
            makePreprocessedFile: True
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - centerCrop(96, 96)
                - virtualScaling(4)
                - sizeMatch()
                - toTensor()
        validation:
            datasetComponent:
                - Vid4, REDS # PARALLEL TODO:
                - Set5       # Serial with List
            batchSize: 1
            samplingCount: 1
            valueRangeType : -1~1
            shuffle: False
            makePreprocessedFile: False
            augmentation:
                - resizeByMaxPixelCount(590000)

        

            
#################################################################################
#                                     TRAIN                                     #
#################################################################################
train:

    step:
        maxEpoch: 180000
        validationStep: 5000
        archiveStep: 100

    hardware:
        GPUNum: 0 # comma-separated

    method:
        mixedPrecision: False 

    dataLoaderNumWorkers: 16







#################################################################################
#                               *** THANK YOU ***                               #
#################################################################################