#################################################################################
#                               *** param.yaml ***                              #
#################################################################################
version : 2.02.200729
 




#################################################################################
#                                     GENERAL                                   #
#################################################################################
general:
    maxMemoryCachingSizeGB: 64
    maxVRAMCachingSizeGB: 8 # will be devide by # of GPU





#################################################################################
#                                       DATA                                    #
#################################################################################
data:
    path: 
        datasetPath: /home/projSR/dataset/
        pretrainedPath: /home/projSR/dataset/pretrained/
    
    datasetComponent:
        DIV2K_SR_train:
            dataConfig: DIV2K_SR
            mode: train # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                scaleMethod: 
                    - bicubic
                scaleFactor: 
                    - 4
            colorMode: color  # 'color' || 'grayscale'
        REDS_train:
            dataConfig: REDS
            mode: train
            classParameter:
                scaleMethod: 
                    - virtual
                scaleFactor: 
                    - 4
            colorMode: color
            sequenceLength: 7 # Only for Image Sequence Dataset
        Vid4:
            dataConfig: Vid4
            mode: test
            classParameter:
                scaleMethod: 
                    - bicubic
                scaleFactor: 
                    - 4
            colorMode: color
            sequenceLength: 7
            #dataset Preprocessing is defined in dataConfig.yaml

    dataLoader:
        train:
            datasetComponent: # Must be list
                - DIV2K_SR_train
            batchSize: 12
            samplingCount: 1
            sameOutputSize: False
            valueRangeType : -1~1
            shuffle: True
            makePreprocessedFile: False
            augmentation: # Must be list of dict
                - centerCrop(256, 256)
        validation:
            datasetComponent:
                - Vid4
            batchSize: 1
            samplingCount: 1
            sameOutputSize: False
            valueRangeType : -1~1
            shuffle: False
            makePreprocessedFile: False
            augmentation:
                - resizeByMaxPixelCount(590000)

        

            
#################################################################################
#                                     TRAIN                                     #
#################################################################################
train:

    step:
        maxEpoch: 180000
        validationStep: 5000
        archiveStep: 100

    hardware:
        GPUNum: 0 # comma-separated

    method:
        mixedPrecision: False 

    dataLoaderNumWorkers: 16







#################################################################################
#                               *** THANK YOU ***                               #
#################################################################################