#################################################################################
#                               *** param.yaml ***                              #
#################################################################################
version : 2.08.201230
 




#################################################################################
#                                     GENERAL                                   #
#################################################################################
general:
    #maxMemoryCachingSizeGB: 64
    #maxVRAMCachingSizeGB: 8 # will be devide by # of GPU
    GPUNum: 1 # comma-separated





#################################################################################
#                                       DATA                                    #
#################################################################################
data:
    path: 
        datasetPath: /home/jovyan/data-vol-1/dataset/
        pretrainedPath: /home/jovyan/data-vol-1/dataset/pretrained/
    


    datasetComponent:
    
        DIV2K_SR_train:
            dataConfig: DIV2K_SR
            mode: train # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                scaleMethod: 
                    - bicubic
                scaleFactor: 
                    - 4
            colorMode: color  # 'color' || 'grayscale'

        DIV2K_SR_train_noised:
            dataConfig: DIV2K_SR
            mode: train
            classParameter:
                scaleMethod:
                    - mild
                    - difficult
                    - unknown
                scaleFactor: 
                    - 4
            colorMode: color  # 'color' || 'grayscale'

        DIV2K_SR_validation:
            dataConfig: DIV2K_SR
            mode: validation
            classParameter:
                scaleMethod: 
                    - bicubic
                scaleFactor: 
                    - 4
            colorMode: color  # 'color' || 'grayscale'

        DIV2K_SR_train_virtual:
            dataConfig: DIV2K_SR_V
            mode: train # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                class: 
                    - GT
            colorMode: color  # 'color' || 'grayscale'

        291_SR_train_virtual:
            dataConfig: 291_SR
            mode: train
            classParameter:
                class: 
                    - GT
            colorMode: color

        Set5_SR_test:
            dataConfig: Set5_SR
            mode: test
            classParameter:
                scaleMethod:
                    - bicubic
                scaleFactor:
                    - 4
            colorMode: color



    dataLoader:
    
        train:
            datasetComponent: # Must be list
                - DIV2K_SR_train_virtual
                #- 291_SR_train_virtual
            batchSize: 64
            valueRangeType : 0~1
            isEval: False
            makePreprocessedFile: True
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - randomCrop(192,192)
                - virtualScaling(4) 
                #- normalize3Ch(0.485, 0.456, 0.406, 0.229, 0.224, 0.225)
                - toTensor()
                - randomFlip()

        validation:
            datasetComponent: # Must be list
                - Set5_SR_test #_virtual
            batchSize: 1
            valueRangeType : 0~1
            isEval: True
            makePreprocessedFile: True
            augmentation: # Must be list of dict   /   toTensor() Must be here
                #- normalize3Ch(0.485, 0.456, 0.406, 0.229, 0.224, 0.225)
                - toTensor()

        inference:
            datasetComponent: # Must be list
                - Set5_SR_test #_virtual
            batchSize: 1
            valueRangeType: 0~1
            isEval: True
            makePreprocessedFile: False
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - toTensor()



            
#################################################################################
#                                     TRAIN                                     #
#################################################################################
train:

    step:
        maxEpoch: 180000
        validationStep: 100
        archiveStep: 100
        earlyStopStep: -1

    method:
        mixedPrecision: False 

    dataLoaderNumWorkers: 1




#################################################################################
#                                   INFERENCE                                   #
#################################################################################
inference:

    

#################################################################################
#                                     SAVE                                      #
#################################################################################
save:

    font:
        path: "/backbone/misc/LatinModernRomanItalic.otf"

    maxSaveImageNumberTrain: 30







#################################################################################
#                               *** THANK YOU ***                               #
#################################################################################
