#################################################################################
#                               *** param.yaml ***                              #
#################################################################################




#################################################################################
#                                       DATA                                    #
#################################################################################
data:
    path: 
        datasetPath: /home/dxlab/jupyter/dogun/License Plate Recognition/dataset/forFramework/
        pretrainedPath: /home/dxlab/jupyter/dogun/License Plate Recognition/dataset/forFramework/pretrained/
    


    datasetComponent:

        LBLP_LLE_virtual:
            dataConfig: LBLP_SR
            out:
                LL:
                    type: Image
                    classParameter:
                        mode:
                            - train
                        scaleMethod:
                            - GT
                GT:
                    type: Image
                    classParameter:
                        mode:
                            - train
                        scaleMethod:
                            - GT


        LP_Unified_virtual:
            dataConfig: LP_Unified_V
            out:
                LR:
                    type: Image
                    classParameter:
                        mode:
                            - train
                            - validation
                        scaleMethod:
                            - GT
                GT:
                    type: Image
                    classParameter:
                        mode:
                            - train
                            - validation
                        scaleMethod:
                            - GT

        LP_China_virtual:
            dataConfig: LP_China_V
            out:
                LR:
                    type: Image
                    classParameter:
                        mode:
                            - train
                            - validation
                        scaleMethod:
                            - GT
                GT:
                    type: Image
                    classParameter:
                        mode:
                            - train
                            - validation
                        scaleMethod:
                            - GT

        New_Lp_256_Blur_HR_test:
            dataConfig: New_Lp_256_Blur_HR
            out:
                LR:
                    type: Image
                    classParameter:
                        mode:
                            - test
                        scaleMethod:
                            - bicubic
                        scaleFactor:
                            - 4
                GT: 
                    type: Image
                    classParameter:
                        mode:
                            - test
                        scaleMethod:
                            - GT

        New_Lp_256_Blur_HR_train_virtual:
            dataConfig: New_Lp_256_Blur_HR_V
            out:
                LR:
                    type: Image
                    classParameter:
                        mode:
                            - train
                        scaleMethod:
                            - GT
                GT: 
                    type: Image
                    classParameter:
                        mode:
                            - train
                        scaleMethod:
                            - GT



    dataLoader:

        train:
            datasetComponent: # Must be list
                - LP_Unified_virtual
                - LP_China_virtual
                - New_Lp_256_Blur_HR_train_virtual
            batchSize: 24
            type: float
            range: 0~1
            isEval: False
            caching: False
            #sequenceLength: 0
            outOrder: 
                - LR
                - GT
            filter:
                channel: 1~3
                height: 24~
                width: 24~
            augmentation:    
                - toRGB()
                - motionBlur(15, 25, 0, 180, -1, 1)
                - resize(64,160)
                - virtualScaling(4)
                - toTensor()


        validation:
            datasetComponent: # Must be list
                #- LP_Unified_valid_virtual
                #- LP_China_valid_virtual
                - New_Lp_256_Blur_HR_test
            batchSize: 1
            type: float
            range: 0~1
            isEval: True
            caching: False
            outOrder: 
                - LR
                - GT

            augmentation: # Must be list of dict   /   toTensor() Must be here    
                - resize(64,160)
                - toTensor()


        inference:
            datasetComponent: # Must be list
                - New_Lp_256_Blur_HR_test #_virtual
            batchSize: 1
            type: float
            range: 0~1
            isEval: True
            caching: False
            
            outOrder: 
                - LR
                - GT
            filter:
                channel: 1~3
                height: 24~
                width: 24~
            augmentation: # Must be list of dict   /   toTensor() Must be here     
                - resize(64,160)
                - toTensor() 



            
#################################################################################
#                                     TRAIN                                     #
#################################################################################
train:

    step:
        maxEpoch: 180000
        validationStep: 20
        archiveStep: 20
        earlyStopStep: -1

    method:
        mixedPrecision: False

    dataLoaderNumWorkers: 0




#################################################################################
#                                   INFERENCE                                   #
#################################################################################
inference:

    

#################################################################################
#                                     SAVE                                      #
#################################################################################
save:

    font:
        path: "/backbone/misc/LatinModernRomanItalic.otf"

    maxSaveImageNumberTrain: 64
    remainOnlyLastSavedResult: False





#################################################################################
#                                     GENERAL                                   #
#################################################################################
general:
    #maxMemoryCachingSizeGB: 64
    #maxVRAMCachingSizeGB: 8 # will be devide by # of GPU
    GPUNum: 2 # comma-separated






#################################################################################
#                               *** THANK YOU ***                               #
#################################################################################
