#################################################################################
#                               *** param.yaml ***                              #
#################################################################################
version : 2.09.210125
 




#################################################################################
#                                     GENERAL                                   #
#################################################################################
general:
    #maxMemoryCachingSizeGB: 64
    #maxVRAMCachingSizeGB: 8 # will be devide by # of GPU
    GPUNum: 3 # comma-separated





#################################################################################
#                                       DATA                                    #
#################################################################################
data:
    path: 
        datasetPath: /home/jovyan/data-vol-1/dataset/
        pretrainedPath: /home/jovyan/data-vol-1/dataset/pretrained/
    


    datasetComponent:
    
        DIV2K_SR_train:
            dataConfig: DIV2K_SR
            mode: train # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                scaleMethod: 
                    - bicubic
                scaleFactor: 
                    - 4
            colorMode: color  # 'color' || 'grayscale'

        DIV2K_SR_train_noised:
            dataConfig: DIV2K_SR
            mode: train
            classParameter:
                scaleMethod:
                    - mild
                    - difficult
                    - unknown
                scaleFactor: 
                    - 4
            colorMode: color  # 'color' || 'grayscale'

        DIV2K_SR_validation:
            dataConfig: DIV2K_SR
            mode: validation
            classParameter:
                scaleMethod: 
                    - bicubic
                scaleFactor: 
                    - 4
            colorMode: color  # 'color' || 'grayscale'

        DIV2K_SR_train_virtual:
            dataConfig: DIV2K_SR_V
            mode: train # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                class: 
                    - GT
            colorMode: color  # 'color' || 'grayscale'

        291_SR_train_virtual:
            dataConfig: 291_SR
            mode: train
            classParameter:
                class: 
                    - GT
            colorMode: color

        Set5_SR_test:
            dataConfig: Set5_SR
            mode: test
            classParameter:
                scaleMethod:
                    - bicubic
                scaleFactor:
                    - 4
            colorMode: color

        Satellite_DOTA_SR_train_virtual:
            dataConfig: Satellite_DOTA_SR_V
            mode: train # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                class: 
                    - GT
            colorMode: color  # 'color' || 'grayscale'

        Satellite_DOTA_SR_validation_virtual:
            dataConfig: Satellite_DOTA_SR_V
            mode: validation # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                class: 
                    - GT
            colorMode: color  # 'color' || 'grayscale'

        Satellite_DOTA_SR_test_virtual:
            dataConfig: Satellite_DOTA_SR_V
            mode: test # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                class: 
                    - GT
            colorMode: color  # 'color' || 'grayscale'

        Satellite_xView_Building_SR_train:
            dataConfig: Satellite_xView_Building_SR
            mode: train # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                class: 
                    - GT
            colorMode: color  # 'color' || 'grayscale'

        Satellite_xView_Building_SR_validation:
            dataConfig: Satellite_xView_Building_SR
            mode: validation # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                class: 
                    - GT
            colorMode: color  # 'color' || 'grayscale'

        Satellite_xView_Building_SR_test:
            dataConfig: Satellite_xView_Building_SR
            mode: test # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                class: 
                    - GT
            colorMode: color  # 'color' || 'grayscale'

        Medical_DeepLesion_Key_SR_train:
            dataConfig: Medical_DeepLesion_Key_SR
            mode: train # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                class: 
                    - GT
            colorMode: color  # 'color' || 'grayscale'

        Medical_DeepLesion_Key_SR_validation:
            dataConfig: Medical_DeepLesion_Key_SR
            mode: validation # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                class: 
                    - GT
            colorMode: color  # 'color' || 'grayscale'

        Medical_DeepLesion_Key_SR_test:
            dataConfig: Medical_DeepLesion_Key_SR
            mode: test # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                class: 
                    - GT
            colorMode: color  # 'color' || 'grayscale'

        Medical_CXR8_SR_train:
            dataConfig: Medical_CXR8_SR
            mode: train # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                class: 
                    - GT
            colorMode: color  # 'color' || 'grayscale'

        Medical_CXR8_SR_validation:
            dataConfig: Medical_CXR8_SR
            mode: validation # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                class: 
                    - GT
            colorMode: color  # 'color' || 'grayscale'

        Medical_CXR8_SR_test:
            dataConfig: Medical_CXR8_SR
            mode: test # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                class: 
                    - GT
            colorMode: color  # 'color' || 'grayscale'

    dataLoader:
    
        train_x:
            datasetComponent: # Must be list
                - DIV2K_SR_train_virtual
                #- 291_SR_train_virtual
            batchSize: 64
            valueRangeType : 0~1
            isEval: False
            makePreprocessedFile: True
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - randomCrop(192,192)
                - virtualScaling(4) 
                #- normalize3Ch(0.485, 0.456, 0.406, 0.229, 0.224, 0.225)
                - toTensor()
                - randomFlip()

        train_x:
            datasetComponent: # Must be list
                - Satellite_xView_Building_SR_train
            batchSize: 128
            valueRangeType : -1~1
            isEval: False
            makePreprocessedFile: False
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - virtualScaling(4)
                - randomCropWithRandomSize(64, 64, 384, 384, 4)
                - shrinkWithRandomMethod(64, 64)
                - randomFlip()
                - toTensor()

        train_x:
            datasetComponent: # Must be list
                - Satellite_DOTA_SR_train_virtual
            batchSize: 64
            valueRangeType : -1~1
            isEval: False
            makePreprocessedFile: False
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - matchChannel(3)
                - randomCropWithRandomSize(64, 64, 256, 256, 4)
                - resize(64, 64)
                - virtualScaling(4)
                - randomFlip()
                - toTensor()

        train_x:
            datasetComponent: # Must be list
                - Medical_DeepLesion_Key_SR_train
            batchSize: 64
            valueRangeType : -1~1
            isEval: False
            makePreprocessedFile: False
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - matchChannel(3)
                - randomCropWithRandomSize(256, 256, 512, 512, 4)
                - resize(256, 256)
                - virtualScaling(4)
                - randomFlip()
                - toTensor()

        train:
            datasetComponent: # Must be list
                - Medical_CXR8_SR_train
            batchSize: 96
            valueRangeType : -1~1
            isEval: False
            makePreprocessedFile: False
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - toRGB()
                - randomCropWithRandomSize(64, 64, 256, 256, 4)
                - resize(64, 64)
                - virtualScaling(4)
                - randomFlip()
                - toTensor()
                
        validation_x:
            datasetComponent: # Must be list
                - Set5_SR_test #_virtual
            batchSize: 1
            valueRangeType : 0~1
            isEval: True
            makePreprocessedFile: False
            augmentation: # Must be list of dict   /   toTensor() Must be here
                #- normalize3Ch(0.485, 0.456, 0.406, 0.229, 0.224, 0.225)
                - toTensor()

        validation_x:
            datasetComponent: # Must be list
                - Satellite_xView_Building_SR_validation #_virtual
            batchSize: 1
            valueRangeType : -1~1
            isEval: True
            makePreprocessedFile: False
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - randomCropWithRandomSize(32, 32, 256, 256, 4)
                - shrinkWithRandomMethod(32, 32)
                - virtualScaling(4)
                - toTensor()

        validation_x:
            datasetComponent: # Must be list
                - Satellite_DOTA_SR_validation_virtual #_virtual
            batchSize: 1
            valueRangeType : -1~1
            isEval: True
            makePreprocessedFile: False
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - randomCropWithRandomSize(32, 32, 256, 256, 4)
                - shrinkWithRandomMethod(32, 32)
                - virtualScaling(4)
                - toTensor()

        validation_x:
            datasetComponent: # Must be list
                - Medical_DeepLesion_Key_SR_validation #_virtual
            batchSize: 1
            valueRangeType : -1~1
            isEval: True
            makePreprocessedFile: False
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - randomCropWithRandomSize(256, 256, 512, 512, 4)
                - shrinkWithRandomMethod(256, 256)
                - virtualScaling(4)
                - toTensor()

        validation:
            datasetComponent: # Must be list
                - Medical_CXR8_SR_validation #_virtual
            batchSize: 1
            valueRangeType : -1~1
            isEval: True
            makePreprocessedFile: False
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - toRGB()
                - randomCropWithRandomSize(64, 64, 256, 256, 4)
                - shrinkWithRandomMethod(64, 64)
                - virtualScaling(4)
                - toTensor()

        inference_x:
            datasetComponent: # Must be list
                - Set5_SR_test #_virtual
            batchSize: 1
            valueRangeType: 0~1
            isEval: True
            makePreprocessedFile: False
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - toTensor()

        inference_x:
            datasetComponent: # Must be list
                - Satellite_DOTA_SR_test #_virtual
            batchSize: 1
            valueRangeType: -1~1
            isEval: True
            makePreprocessedFile: False
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - toRGB()
                - randomCrop(64, 64)
                #- virtualScaling(4)
                - toTensor()

        inference:
            datasetComponent: # Must be list
                - Medical_CXR8_SR_test #_virtual
            batchSize: 1
            valueRangeType: -1~1
            isEval: True
            makePreprocessedFile: False
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - toRGB()
                #- randomCrop(256, 256)
                #- virtualScaling(4)
                - toTensor()



            
#################################################################################
#                                     TRAIN                                     #
#################################################################################
train:

    step:
        maxEpoch: 180000
        validationStep: 20
        archiveStep: 20
        earlyStopStep: -1

    method:
        mixedPrecision: False 

    dataLoaderNumWorkers: 1




#################################################################################
#                                   INFERENCE                                   #
#################################################################################
inference:

    

#################################################################################
#                                     SAVE                                      #
#################################################################################
save:

    font:
        path: "/backbone/misc/LatinModernRomanItalic.otf"

    maxSaveImageNumberTrain: 30







#################################################################################
#                               *** THANK YOU ***                               #
#################################################################################
