#################################################################################
#                               *** param.yaml ***                              #
#################################################################################
version : 2.04.200820
 




#################################################################################
#                                     GENERAL                                   #
#################################################################################
general:
    #maxMemoryCachingSizeGB: 64
    #maxVRAMCachingSizeGB: 8 # will be devide by # of GPU
    GPUNum: 0 # comma-separated





#################################################################################
#                                       DATA                                    #
#################################################################################
data:
    path: 
        datasetPath: /home/projSR/dataset/
        pretrainedPath: /home/projSR/dataset/pretrained/
    
    datasetComponent:
        DIV2K_SR_train:
            dataConfig: DIV2K_SR
            mode: train # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                scaleMethod: 
                    - bicubic
                scaleFactor: 
                    - 4
            colorMode: color  # 'color' || 'grayscale'

        DIV2K_SR_train_virtual:
            dataConfig: DIV2K_SR_V
            mode: train # 'train' || 'validation' || 'test'.  # See above table
            classParameter:
                class: 
                    - GT
            colorMode: color  # 'color' || 'grayscale'

        291_SR_train:
            dataConfig: 291_SR
            mode: train
            classParameter:
                class: 
                    - GT
            colorMode: color

        REDS_SR_train:
            dataConfig: REDS_SR
            mode: train
            classParameter:
                degradationMethod:
                    - sharp_bicubic
                scaleFactor:
                    - 4
            colorMode: color


        VID4_SR_test:
            dataConfig: VID4_SR
            mode: test
            classParameter:
                degradationMethod:
                    - bicubic
                scaleFactor:
                    - 4
            colorMode: color


    dataLoader:
        train:
            datasetComponent:
                - REDS_SR_train
                #- VID4_SR_test
            batchSize: 8
            valueRangeType : -1~1
            isEval: False
            makePreprocessedFile: True
            sequenceLength: 5
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - centerCrop(96, 96)
                #- sizeMatch()
                - toTensor()
        validation:
            datasetComponent:
                - REDS_SR_train
                #- VID4_SR_test
            batchSize: 8
            valueRangeType : -1~1
            isEval: False
            makePreprocessedFile: True
            sequenceLength: 5
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - centerCrop(96, 96)
                #- sizeMatch()
                - toTensor()
        inference:
            datasetComponent: # Must be list
                - DIV2K_SR_train
            batchSize: 32
            valueRangeType : -1~1
            isEval: False
            makePreprocessedFile: True
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - centerCrop(96, 96)
                - sizeMatch()
                - toTensor()
        train_y:
            datasetComponent: # Must be list
                - 291_SR_train
                - DIV2K_SR_train_virtual
            batchSize: 30
            valueRangeType : -1~1
            isEval: False
            makePreprocessedFile: True
            augmentation: # Must be list of dict   /   toTensor() Must be here
                - centerCrop(96, 96)
                - virtualScaling(4)
                - sizeMatch()
                - toTensor()

        #validation:
        #    datasetComponent:
        #        - Vid4, REDS # PARALLEL TODO:
        #        - Set5       # Serial with List
        #    batchSize: 1
        #    valueRangeType : -1~1
        #    isEval: False
        #    makePreprocessedFile: False
        #    augmentation:
        #        - resizeByMaxPixelCount(590000)

        

            
#################################################################################
#                                     TRAIN                                     #
#################################################################################
train:

    step:
        maxEpoch: 180000
        validationStep: 1
        archiveStep: 100

    method:
        mixedPrecision: False 

    dataLoaderNumWorkers: 16







#################################################################################
#                               *** THANK YOU ***                               #
#################################################################################